# Site settings
title: The Beacon
organization: "The William F. Buckley, Jr. Program at Yale"
email: inquiry@buckleyprogram.com
twitter: "buckleyprogram"
facebook: "Buckley Program"
github: zyoung14
description: "The Buckley Program offers a speaker series, conferences, Firing Line debates, funded summer internships and more. Its mission is to promote intellectual diversity at Yale."
baseurl: http://zyoung14.github.io

# Build settings
markdown: kramdown
permalink: pretty
