# Site settings
title: The Beacon
organization: "The William F. Buckley, Jr. Program at Yale"
email: inquiry@buckleyprogram.com
twitter: "buckleyprogram"
facebook: "Buckley Program"
github: zyoung14
description: "The Buckley Program's offerings include a speaker series, conferences, Firing Line debates and funded summer internships. Its mission is to promote intellectul diversity at Yale."
baseurl: http://zyoung14.github.io

# Build settings
markdown: kramdown
permalink: pretty
